### ISSUE TITLE
Change in spack failure of automated build

### ISSUE THREAD

**Issue by vsoch** [dyninst/dyninst#1194]
@hainest this is for you! Slack is on my other computer and I'm too lazy to walk 20 feet at the moment :)

```bash
2022-02-02T03:34:23.4886639Z ==> Fetching https://mirror.spack.io/_source-cache/archive/7f/7f6fb9149b1673d38d9178a0d3e0fb8a1ec4f53a9f4c2ff89469609879641177.tar.bz2
2022-02-02T03:34:23.4887050Z ==> Ran patch() for elfutils
2022-02-02T03:34:23.4980124Z ==> elfutils: Executing phase: 'autoreconf'
2022-02-02T03:34:23.5135765Z ==> elfutils: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 77:
    '/tmp/root/spack-stage/spack-stage-elfutils-0.186-64o7eqipg4bxe52irdh5qohwsuk63o5b/spack-src/configure' '--prefix=/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.0.1/elfutils-0.186-64o7eqipg4bxe52irdh5qohwsuk63o5b' '--without-bzlib' '--without-lzma' '--with-zlib=/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.0.1/zlib-1.2.11-oski6wpiq4xvenaqdds4anr4cnutrswy' 'LDFLAGS=-Wl,--no-as-needed -L/usr/lib -lintl' '--disable-debuginfod' '--disable-libdebuginfod'

2 errors found in build log:
     13    checking whether make supports nested variables... (cached) yes
     14    checking build system type... x86_64-pc-linux-gnu
     15    checking host system type... x86_64-pc-linux-gnu
     16    checking whether make supports the include directive... yes (GNU sty
           le)
     17    checking for gcc... /opt/spack/lib/spack/env/gcc/gcc
     18    checking whether the C compiler works... no
  >> 19    configure: error: in `/tmp/root/spack-stage/spack-stage-elfutils-0.1
           86-64o7eqipg4bxe52irdh5qohwsuk63o5b/spack-src':
  >> 20    configure: error: C compiler cannot create executables
     21    See `config.log' for more details

See build log for details:
  /tmp/root/spack-stage/spack-stage-elfutils-0.186-64o7eqipg4bxe52irdh5qohwsuk63o5b/spack-build-out.txt

==> Updating view at /opt/dyninst-env/.spack-env/view
```

It looks like something has changed in spack so our base container failed today. Unlike last time I don't see any changes to the failing package - indeed it's the same release from last year (and the build from yesterday worked):

```bash
==> Installing elfutils-0.186-iosmb7qegoihv4h2wsrftodkoykcjyd4
==> No binary for elfutils-0.186-iosmb7qegoihv4h2wsrftodkoykcjyd4 found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/7f/7f6fb9149b1673d38d9178a0d3e0fb8a1ec4f53a9f4c2ff89469609879641177.tar.bz2
==> Ran patch() for elfutils
==> elfutils: Executing phase: 'autoreconf'
==> elfutils: Executing phase: 'configure'
==> elfutils: Executing phase: 'build'
==> elfutils: Executing phase: 'install'
==> elfutils: Successfully installed elfutils-0.186-iosmb7qegoihv4h2wsrftodkoykcjyd4
  Fetch: 0.66s.  Build: 1m 4.47s.  Total: 1m 5.13s.
```
It seems to be the same source code from the cache, so it can't be that (7f6fb9149b1673d38d9178a0d3e0fb8a1ec4f53a9f4c2ff89469609879641177). The only change in elfutils was adding a patch for Mac, which only should be applied for [gcc 11.2.0](https://github.com/spack/spack/commit/80a3f01bbbb6304ee4791720279b29d59c799ec7#diff-5089344542ef0a05b823ba5a050403c20febec624522362959d5be1de9a07c59). 

One thing I don't quite understand is why it's using `/opt/spack/lib/spack/env/gcc/gcc` when we have the gcc on the system as a virtual dependency. It could be that if it's trying to use the default, 11.2.0, the patch would be applied and it might result in this "does not create executables" business. I'm going to ping @alalazo to see if he has insight to why:

1. the install might be using some different version of gcc installed with spack (which would default to the last 11.2.0 if relecant)
2. and if so, why this patch https://github.com/spack/spack/commit/80a3f01bbbb6304ee4791720279b29d59c799ec7#diff-a108a05bff2c1ef067255bebfad8328ab4d999225ed88631766160c5f77b7a7c is being applied without checking that we are on a mac possibly resulting in this issue?

And just for kicks and giggles I'm going to re-run in case spack was just being a :hankey: face. If it errors again, @alalazo let me know what you'd like to see in the build to debug and I'll make it so!

**Comment by alalazo** [comment]
> One thing I don't quite understand is why it's using /opt/spack/lib/spack/env/gcc/gcc when we have the gcc on the system as a virtual dependency.

Hi @vsoch The path you see is that of the compiler wrapper that Spack uses to e.g. inject RPATHs and do other flag manipulations. It's basically a middle layer that we added to intercept the compilation command, transform it and forward to the real compiler being used. The wrapper at the moment is a single file (the one called `cc`) while all the other names are symlinks. It's like that because it turns out some configuration scripts use the executable name to detect which compiler they're being configured with :grimacing:

**Comment by alalazo** [comment]
> we have the gcc on the system as a **virtual dependency**

I don't understand this part. In the future compilers might be "external" (not virtual) dependencies but we're not there right now. At the moment compilers are modeled as node attributes in the DAG. Each one of them potentially aggregates 3 languages (C, C++, Fortran), is represented by a "name" and a "version" and configured in `compilers.yaml`.

**Comment by alalazo** [comment]
To answer your questions:
1. From the snippet you posted it seems to me that you are using `gcc@11.0.1` (that's what's encoded in the path of the failing build stage). 
2. The patch in GCC is conditional on the host platform being `darwin` and the macOS version being greater than 10.15, see [here](https://github.com/spack/spack/blob/80a3f01bbbb6304ee4791720279b29d59c799ec7/var/spack/repos/builtin/packages/gcc/package.py#L241-L264)

I agree that it would be better expressed as a spec, but I opted for a one line change instead of a complete refactor of that section.

**Comment by vsoch** [comment]
The RSE-ops images are failing too because of the same reason - https://github.com/rse-ops/docker-images/runs/5031468261?check_suite_focus=true I have to conclude something changed in spack to lead to this. Aside to pinning to a commit from a day ago how do we fix this?

**Comment by vsoch** [comment]
And I meant external not virtual, I just used the wrong word :p

**Comment by alalazo** [comment]
Reposting here the conversation on Slack. The difference between the last [passing](https://github.com/rse-ops/docker-images/runs/5015885143?check_suite_focus=true) build:
```console
2022-02-01T03:19:15.7889402Z ==> gettext: Executing phase: 'autoreconf'
2022-02-01T03:19:15.8109787Z ==> gettext: Executing phase: 'configure'
2022-02-01T03:21:06.5163760Z ==> gettext: Executing phase: 'build'
2022-02-01T03:24:51.9042563Z ==> gettext: Executing phase: 'install'
2022-02-01T03:25:10.1606468Z ==> gettext: Successfully installed gettext-0.21-677nbwngisllmk76fpfcda2256fylgwm
2022-02-01T03:25:10.1607415Z   Fetch: 1.03s.  Build: 5m 54.65s.  Total: 5m 55.68s.
2022-02-01T03:25:10.1610656Z [+] /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/gettext-0.21-677nbwngisllmk76fpfcda2256fylgwm
```
and the last [failing](https://github.com/rse-ops/docker-images/runs/5031468340?check_suite_focus=true) build:
```console
2022-02-02T03:14:46.1526312Z [+] /usr (external gettext-0.19.8.1-yveesvsznw54wh2lbjeac3m4h6wh23vf)
```
seems to be that `gettext`, which is a dependency of the failing `binutils` build, started to be discovered as an external. The corresponding commit is:
```
commit c3bad2a93566b433149856933acdb9040e3c7129
Author: Nils Leif Fischer <nils.fischer@aei.mpg.de>
Date:   Tue Feb 1 12:25:02 2022 +0100

    gettext: find external (#28610)
```
[here](https://github.com/spack/spack/pull/28610) the associated PR. Hope it helps.

**Comment by vsoch** [comment]
What do you suggest we do? This seems like a bad PR to merge I suspect it’s going to break many builds.

**Comment by alalazo** [comment]
Not sure. I think it's just incomplete, partially because of the simplified model we have right now for externals:
1. sub-graphs are trimmed and inconsistencies might happen with the external dependencies
2. finding externals is currently restricted to just inspecting executables - we have no mechanism to check if some headers or libraries are available and many times a package in Spack is split into multiple packages at the system level e.g. `X` and `X-dev`

Is that an option for you to explicitly select the externals you want to use instead of searching for everything Spack knows about? Or checking if some system packages are missing to have the external `gettext` usable in a Spack build?

**Comment by alalazo** [comment]
For reference @bvanessen and @scheibelp are working on https://github.com/spack/spack/pull/28005 to extend the capability of `external find` beyond just executables.
