### ISSUE TITLE
Wrong size returned for Memory reference involved operand in Control Flow instruction. (Version 12.0.1)

### ISSUE THREAD

**Issue by jqhong** [dyninst/dyninst#1258]
**Intention**
May I confirm if it is a bug in Dyninst Version 12.0.1. 

**Describe the bug**
The **SIZE** evaluated for memory reference operand in _Control Flow Instruction_ seems wrong. Operand->getValue()->size() is the API that I invoked to get the size.  **The platform is Arch_x86_64**.  I tried on several different types of instructions.

For **jmp/call through Memory** instructions, such as jmpq *(%rdi); jmpq *0x8(%rip); call *0xff(%rdi); the size returned are all **4-byte**, while the expected ones are 8-byte.
For **jmp/call through register** instructions, such as jmp *%rdi; the size returned is 8-byte as expected. 
For **direct jmp/call**, the size or destination evaluated is also as expected 8-byte. 
Then, I also tried on other type of instructions, such as mov (%rip), %rax; The size for its two operands are also 8-byte as expected. 

So, I want to confirm that the size returned for operand in ** _jmp/call through Memory instruction_** is **WRONG** (I expect 8-byte, but it returns 4-byte). 

You can try it on any elf file which contains a **jmp/call through Memory** instruction (on x86_64 platform).

**Comment by OnsiteAnalysis** [comment]
[code.zip](https://github.com/dyninst/dyninst/files/8580199/code.zip)
Please find attached.  
tt.c is the source file, tt is the compiled elf. _The tested three instructions are in function main from 0x617-0x624_. The operand size evaluated using _Operand->getValue()->size()_ is **4** instead of **8**. 
Please DO NOT execute the tt file, since it will cause a segmentation fault.

**Comment by jqhong** [comment]
[code.zip](https://github.com/dyninst/dyninst/files/8580251/code.zip)
Please find attached.

_tt.c_ is the source file, _tt_ is the compiled elf. _The tested three instructions are in function main from 0x617-0x624_. The operand size evaluated using _Operand->getValue()->size()_ is **4** instead of **8**.

Please DO NOT execute the _tt_ file, since it will cause a segmentation fault.

**Comment by hainest** [comment]
Thank you for the detailed reproducer. Could you also include a minimum working example of the Dyninst program you wrote to parse the binary? I want to make sure we're using the same methods as you (e.g., symtab vs bpatch).

**Comment by jqhong** [comment]
Sorry that I am not able to provide it, since I replaced the default
CodeSource and use Dyninst to decode instructions from memory directly
instead of from an elf file. Following are the main steps:
1. decode instruction: Instruction I = decoder->decode((unsigned char*)
cr->getPtrToInstruction(InsnAddr));
2. parse operands: I.getoperands(oprands);
3. get the size for each operand and dump to stdout to check: std::cout <<
oprand.getValue()->size() << std::endl;

**Comment by hainest** [comment]
@jqhong We'll try to reproduce this. Thanks for the update.

@bigtrak @kupsch Could one of you take a look when you have some time?

**Comment by bigtrak** [comment]
Thanks for the info about the behavior  you noticed.
I was able to replicate it using the Dyninst examples
disassembler, along with some added code to print operand
sizes (using Dyninst's operand size method).

If we discover any short-term fixes for this, we will notify
you about the change.  

I will re-iterate Tim's earlier comments -- an exact reproducer means
we can examine a problem immediately, instead of having to consume
out debugging time trying to rebuild what you experienced.   If you submit
issues in the future, an example mutator and mutatee (analyzer and code
being analyzed) that can be compiled and run by us is likely to help your
case being solved, instead of just repeated.  
 
That being said, thank you for notifying us of this issue.  We will look into
it in the future.
