### ISSUE TITLE
document proccontrol "tracking" APIs

### ISSUE THREAD

**Issue by cuviper** [dyninst/dyninst#151]
It appears that `proccontrol.pdf` doesn't have any mention of the various tracking APIs -- pretty much everything in `PlatFeatures.h` is missing.

In particular, I found the library tracking controls useful for [rhbz1366574](https://bugzilla.redhat.com/show_bug.cgi?id=1366574), to reduce mutatee impact, but I only discovered this by tracking down that breakpoint's origin to see that it could be disabled.

**Comment by wrwilliams** [comment]
@mplegendre do you have any design docs lying around for these? I expect most of them do what they say on the tin, and most of the ones I'm unsure about are BG/Q, but I'd love to have something canonical from you.

**Comment by mplegendre** [comment]
Sorry for the delayed response. I missed this ping until the recent discussion.

I don't have any internal documentation on these interfaces.  The intent behind the PlatFeatures was to segregate off the non-portable interfaces from the main PC interfaces.  They've somewhat languished because of that segregation.  Some of these interfaces should die with the BG/Q port, and I don't think are worth documenting.  Some of these could be worth supporting long-term and documenting.

The PlatFeatures classes that I'd suggest supporting long-term are:
LibraryTracking, LWPTracking, ThreadTracking, FollowFork, and SignalMask.

The ones I'd suggest dropping are:
CallStackUnwinding, MemoryUsage, MultiToolControl, BGQData, and RemoteIO

**Comment by wrwilliams** [comment]
Are MemoryUsage and RemoteIO doing things that aren't portable off BG/Q, or just things that we haven't generalized/don't need outside BG/Q? Those look like they could represent general concepts (and might apply to accelerators). Obviously non-stackwalker unwinding and true BG/Q specifics should die as soon as we can justify it.

**Comment by mplegendre** [comment]
RemoteIO was intended for when the debugger and debugee don't share a file system, and the debugger triggers IO in the debugee's file system space.  It could conceptually work cross-platform, but I'd suggest just redesigning the interface from scratch if we ever need that functionality again.  The current interface is fairly limited, as the BG/Q debug interface was also very limited.

The MemUsage interface works right now on Linux--it reads /proc/PID/statm.  But I'd vote for ProcControlAPI getting out of the memory usage measurement business.  Our implementation isn't creating a lot of value by reading from /proc, and someone would be making a mistake if they tried to use these numbers in any cross-platform way (e.g, by comparing between platforms).

**Comment by wrwilliams** [comment]
In fixing #224 I dropped in LibraryTracker documentation for Stackwalker that should be an easy copy/paste into ProcControl for the most part. Anyone have cycles for a quick and dirty writeup on LWP and thread tracking, follow fork, and signal mask?
