### ISSUE TITLE
Issue with static instrumentaion on `bodytrack`

### ISSUE THREAD

**Issue by Ouhznehc** [dyninst/dyninst#1635]
Hello, I am encountering an issue when I try to statically insert some instruction into a binary file. In detail, the Dyninst failed to insert the instruction like `nop` or `ptwrite` as I expected. I add error handling in every API but still can not find any errors.  

This [issue.zip](https://github.com/dyninst/dyninst/files/13463948/issue.zip) file contains my rewrite file along with the test binary file named `bodytrack`. You can use `make install` to build the environment and `make run` to rewrite the `bodytrack`. In addition, the `rewrite.cpp` would open `inst.log` which contains information about address and instruction bytes. The rewrite program will then insert the instruction bytes behind the address. My platform is Ubuntu22.04.

Any insights or suggestions would be greatly appreciated as I am currently stuck with this issue.

**Comment by bigtrak** [comment]
In general you have the correct idea.   However, you are trying to modify instructions
by address.   Instead you need to use dyninst "Points" to identify the locations that
you are inserting code at.   In particular, once you start inserting code, it causes code
locations to move.  

I have not tried running your example, but I have used Xiaozhu's similar code which
does work and writes a new binary.   Please checkout https://github.com/mxz297/dyninst-tools
and the InsertCodeBuffer example to see how to go about doing things "The Dyninst Way".

Try using that as a base to see if it works correctly for you, and then if it does, try modifying it
to fit your needs.  I've personally tested that on rhel8, I haven't run it on ubuntu 22, if his example
fails there, please send feedback.

Before I forget -- Which release version of dyninst are you using?  What versions of the base 
dependencies are you using -- intel-tbb, elfutils, boost, and libiberty?  Which compiler and version?

**Comment by Ouhznehc** [comment]
It's such a coincidence that I actually modified my code based on Xiaozhu's code. My code can run normally in some small-scale tests, but when I run the `bodytrack` benchmark, dyninst does not complete the insertion correctly. Additionally, the version of my Dyninst and related dependencies are all provided in my `Makefile`. If you can run this example and help me identify the problem, I would be extremely grateful.

**Comment by bigtrak** [comment]
You may want to take a look at memgaze. It has Dyninst instrumentation based on Xiaozhu's code which does ptwrite instrumentation.  https://github.com/pnnl/memgaze    When I have some time later this week I'll take a brief look at your code.  A working example may be more beneficial to you in the long run as well, or perhaps you might want to check their instrumentor out.

**Comment by bigtrak** [comment]
We are unable at this time to create a 32-bit binary environment to replicate your issues, due to
resource limitations.

However -- I've cmpiled bodytrack, and  made an address list of similar locations in the  x86_64 binary.
I see that Dyninst correctly instruments with your code on x86_64 with a 64bit binary of bodytrack 
compiled on the same platform, at similar locations.   So, your tool is working as an instrumentor.

I'm going to close this issue at this time, as your tool works as you intended.   If you run into problems
with Dyninst failing on 32 bit binary rewrites, please open a separate ticket for that issue, complete
with some examples of what went wrong, and perhaps bundle up more things, such as all the Dyninst
compiled libraries and your tool, and error logs.  Putting that all together to analyze and examine would be a big help.

From your build script, you are building from the head of Dyninst, instead of from the last
Dyninst release.  Our last release is 12.3.0;  If you try that out and it works, and doesn't work
with the head of master, a new issue on 32bit issues with such a note would be appreciated.    I recommend
trying to test on 64bit intel x86_64 as well, which may give you a better idea of it is an issue with your
instrumentor, or with dyninst.
