### ISSUE TITLE
PPC64 generateBranchViaTrap: Assertion `isCall == false' failed.

### ISSUE THREAD

**Issue by cuviper** [dyninst/dyninst#175]
This test tries to attach-mutate-detach twice on the same process: [dynamic-double.zip](https://github.com/dyninst/dyninst/files/462890/dynamic-double.zip)

With Dyninst 9.2 on PPC64 RHEL7.2, this crashes with an assertion the second time around.  It's fine on x86_64, and also fine on PPC64 with 9.1.

```
# ./mutatee & ./mutator $! ; wait
[1] 4194
TAKE1 A
TAKE1 B
TAKE1 C
TAKE1 D
TAKE1 E
TAKE1 F
TAKE1 G
TAKE1 H
TAKE1 I
FUNCTION EXECUTED. VALUE = 1
FIRST MUTATION DONE. MUTATOR IS DOING THE SECOND ONE...
FUNCTION EXECUTED. VALUE = 2
TAKE2 A
TAKE2 B
TAKE2 C
TAKE2 D
TAKE2 E
TAKE2 F
TAKE2 G
mutator: /root/dyninst/dyninstAPI/src/codegen-power.C:259: static void insnCodeGen::generateBranchViaTrap(codeGen&, Dyninst::Address, Dyninst::Address, bool): Assertion `isCall == false' failed.
Aborted
FUNCTION EXECUTED. VALUE = 3
FUNCTION EXECUTED. VALUE = 4
FUNCTION EXECUTED. VALUE = 5
FUNCTION EXECUTED. VALUE = 6
FUNCTION EXECUTED. VALUE = 7
FUNCTION EXECUTED. VALUE = 8
FUNCTION EXECUTED. VALUE = 9
FUNCTION EXECUTED. VALUE = 10
[1]+  Done                    ./mutatee
```

**Comment by wrwilliams** [comment]
Pretty sure the branch format is cosmetic; @jdetter can you confirm?

I suspect that this is a side effect of the RT heap fixes in 9.2, and that we're now needing long branches where we didn't before. The good solution is to have modifyCall (and also modifyJump while we're in here) generate something like the following:

```
spill ctr if live
allocate scratch gpr
generate target in scratch
mtctr scratch
<branch/conditional branch/call> new target
restore spilled regs
```

Because seriously, to hell with traps, we're in relocated code, we have space. And generateBranchViaTrap is an acceptable thing for the springboard code to call--where it's going to generate a branch-by-god.

It seems likely to me that we could pull the strategy associated with generating a far branch/call (build indirect target in register, move to valid register for indirection, emit indirect control flow instruction) into the emitter and virtualize those steps per architecture, if we wanted to make this logic a bit cleaner, too.

**Comment by cuviper** [comment]
Ok, the RTheap idea gives me something to directly try reverting.  I'll report back on that.

**Comment by cuviper** [comment]
Indeed, it works after reverting ce99292ae64e (and 59a466ba2405).

Looking at the infmalloc log, it's trying to get "size 96, type 7, near 0x1000078e (0xe000792 to 0x1200078a)".  The first time around, it mmaps a chunk at 0xe010000 for this.  The second time, it *tries* the same mmap, which is still occupied from before, so the OS hands back 0x3fff76a70000 instead.  Whoever said mmap would try to stay close to the hint was a dirty liar...

On 9.1 it worked because the RTlib used `MAP_FIXED` which will just clobber any existing mapping, but also it was reading `/proc/self/maps` first to be sure it only tried available areas.  We know that's not signal-safe, so it was good to change it, but it did allow the second attachment to find a different mmap nearby.

Does the mutator side have a complete view of the mutatee's memory?  Perhaps it can tweak the constraints to start in a free area before sending the iRPC.

Or perhaps `trymmap` should throw away that address that was wildly out of range and try again.  It's already set up to loop, but I suspect it's currently always "succeeding" the first time.

Improving the codegen for long branches sounds good too, of course.

**Comment by wrwilliams** [comment]
Mutator-side should have a complete view of memory, and it would be good to avoid long branches wherever possible. Furthermore, we shouldn't need to map again; we mapped a page, and we should be able to allocate on that page.

What's DYNINST_DEBUG_INFMALLOC have to say about this?

**Comment by cuviper** [comment]
[debug-dynpc-infmalloc.txt](https://github.com/dyninst/dyninst/files/464687/debug-dynpc-infmalloc.txt)

It appears the second time we attach has no retained knowledge from the first time around.  Which is probably to be expected, because who knows what may have happened to the process in the meantime, or whether that PID is even still the same process.  Since the RTlib stays mapped, I'd expect it will still have the allocation in its global heaplist, but that only appears to be used for frees, never reported to the mutator.

There's probably also a lot of fragility in re-instrumenting a process like this too, clobbering previous state.  Like, if it happened to interrupt the process while it was in a previous relocation, then starts writing new relocations in the same static heap, it could be very bad.  I don't know if there's a safe way to do this...

**Comment by cuviper** [comment]
#176 should fix the infmalloc locality, so it passes the dynamic-double test.

We might still want to keep this issue open for the codegen changes you proposed, but I won't have a direct way to trigger that anymore.

**Comment by wrwilliams** [comment]
It is, I think, in general unsafe to reuse a heap from a previously attached mutator. In order to make that safe, we'd have to move a sufficient amount of internal allocation tracking into the RTlib that it could report on what space remains on each heap.

@cuviper Do you have cycles to try some of the codegen changes before we merge #176 into master and 9.2.1? If not, I can take a stab at them sometime next week but that's the earliest I expect to get to it.

**Comment by cuviper** [comment]
I have a few Dyninst bugs on Fedora to investigate (which I may forward here), then I can probably look at this.  But codegen is still a bit of a black box to me, so I might not be quick about it. :)

I think my first step will be to get a more permanent reproducer for long branches so this doesn't regress, and so we don't have to hold up #176.  There was a similar issue solved in #163 too; in fact I'm going to go see if that was also an infmalloc constraint failure at its core.  That seems likely, so we really need a reliable way to force testing long relocations just in case.

**Comment by wrwilliams** [comment]
Seems we should, in principle, be able to set up some legit unit tests for the Emitter class(es) that mock everything outside (the CodeGen interface we care about is 90% a big buffer-of-bytes) and verify that we can cook up appropriate code sequences. I think that's a better way to go than trying to force long branches in the wild, no?

**Comment by cuviper** [comment]
If we can trigger this in a unit test, that absolutely sounds better.
Is there anything unit-test-y in the testsuite already to start from?

**Comment by wrwilliams** [comment]
Sadly, no, and I realized this opens something of a can of worms.

AsYouKnowBob, the current test suite relies on an installed copy of Dyninst; this means that we can't write tests in the current suite that use non-public interfaces. There are two paths here, and they are likely to both be useful in the end:

1) Reintegrate the test suite repo and use the build tree rather than the install tree to build the test suite. Advantage: unit tests with mock objects surrounding internal classes become easier to write. Disadvantages: involves messing with the test suite's CMake system (though I think that's covered in the test suite merge PR?), and while it's a nominally quite good use of git-subtree, I am given to understand that there are no good uses of git-subtree.
2) Extract some portion of code generation and/or relocation as a separate component, giving it testable public interfaces. Advantage: as per quite a bit of mailing list traffic, this is something that people really, really want. Disadvantage: extracting components is always a nontrivial amount of work.

There is a third, interim path where we could add low-level unit tests that live in the Dyninst source tree and get built and run by 'make check'. These would need to be tests that are sufficiently isolated from system dependencies that all of them run anywhere and we get useful results on each run, but that should be easy to do with code generation--it's semantics in, bytes out and we could verify output with instructionAPI/parseAPI/dataflowAPI if we wanted.

**Comment by cuviper** [comment]
(I would expect the reintegrated testsuite to be a one-time import, discontinuing the standalone tree, so that's probably the best possible use of git-subtree.)
