### ISSUE TITLE
Analyzing functions in acroRd32.dll (large binary without symbols)

### ISSUE THREAD

**Issue by sborpo** [dyninst/dyninst#179]
Hello,
i have tried to analyze the number of functions in acroRd32.dll (Adobe reader dll ~20Mb).
The analysis results in  14,527 functions  , it's far less than ida's result : ~160,000 functions.
Does someone have a clue what might be the problem?

Here is the code that i run:
```
#include <stdio.h>
#define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS 1
#include "CodeObject.h"
#include "InstructionDecoder.h"

using namespace std;
using namespace Dyninst;
using namespace ParseAPI;


int main()
{
	char * binaryPath = "C:\\AcroRd32.dll";
	SymtabCodeSource * sts;
	CodeObject * co;
	sts = new SymtabCodeSource(binaryPath);
	co = new CodeObject(sts);
	co->parse();
	const CodeObject::funclist &all = co->funcs();
	cout << all.size();
	return 0;
}`
```

**Comment by mxz297** [comment]
At the parseAPI level, the `CodeObject::parse() ` interface will not invoke gap parsing. You can instead use `CodeObject::parseGaps(CodeRegion *cr)` to do function entry identification on binaries without symbols. Hope the following code snippet helps:

```
 vector<CodeRegion*> regs = sts->regions();
 for (auto rit = regs.begin(); rit != regs.end(); ++rit) {
        CodeRegion *reg = *rit;
        co->parseGaps(reg);    
 }
```

**Comment by sborpo** [comment]
Thanks for quick reply  :) 
The code snippet helped and now it seems like it really make the hard analysis.
Unfortunately the analysis crashes on acroRd32 after long time with an abort message. 
It seems like an assert problem (I've tested it with a debug target compiled version - i will try to complie it to release and retry it) 

Just to try how it works on other dll - i checked it out on Qt5Core.dll , after the analysis it discovered ~11,000 functions , i have compared it with IDA - there i saw ~17,500
Do you have an idea why the difference is so big ? Can i run other api calls that will improve the results?

Thanks!

**Comment by mxz297** [comment]
The Visual Studio is not ABI compatible across optimization levels. So, if you compile Dyninst with one optimization level and compile your Dyninst application with a different optimization level, it is not surprising that you would see an assert. 

In terms of why you see a significant difference between the results reported by Dyninst and IDA Pro, the root reason is that recovering function entries from stripped binaries is a best effort task and Dyninst and IDA Pro use different approaches to attack this problem. Neither Dyninst nor IDA Pro can guarantee that all reported functions are real functions.

In my experiences, IDA Pro does often report more "functions" than Dyninst. But when I inspected these functions reported by IDA Pro, many of these functions were marked "failed" by IDA Pro and did not seem to be real functions. Since you have access to IDA Pro, you can sample a few functions reported by IDA Pro, but not reported by Dyninst, and see whether they look like real functions.

**Comment by wrwilliams** [comment]
@sborpo Is this now resolved with @mxz297's help, or is there an active bug here?

**Comment by wrwilliams** [comment]
Closing.
