### ISSUE TITLE
Race conditions with transient threads

### ISSUE THREAD

**Issue by cuviper** [dyninst/dyninst#208]
I've been staring at [rhbz1373197](https://bugzilla.redhat.com/show_bug.cgi?id=1373197) too long -- time to involve you folks here.  (I probably should have just filed this a while ago, sorry.)

The test mutator simply detaches and reattaches the target over and over.  It has a watchdog thread to make sure we're making progress.  Sometimes this watchdog triggers, indicating something stalled, and sometime the reattach just fails outright.  I've added code to write a `debug-proccontrol` file too.

The test mutatee simply spawns a thread, and that thread waits 100ms before spawning a new copy of itself.  So threads are coming and going fairly frequently, and it makes it pretty reproducible for proccontrol to race on these events while reattaching.

[proccontrol-thread-race.zip](https://github.com/dyninst/dyninst/files/539952/proccontrol-thread-race.zip)

Run the `thready` mutatee in the background or in a different terminal, then find its PID and run `dyninst-reattach-loop PID`.  The time to getting stuck/failure varies a lot, but it inevitably does hit one of the races eventually.

Broadly speaking, the "stuck" case seems to consistently be that it sends a manual SIGSTOP, and never sees an event after that.  I never see this manual SIGSTOP otherwise, until we get to this bad case.  The direct "failed" case seems to be that it's trying to read /proc/PID/stat for a thread that already exited (known from the previous attachment?), and it bails entirely.  I'm not sure how to fix either case.

**Comment by cuviper** [comment]
I've tried changing the mutator to use a full `detach` and `attachProcess` loop (vs. `temporaryDetach` and `reattach`), but it still sometimes hits the failed case trying to read a dead stat.  But I also get an occasional assertion failure, which I've never seen in the `reattach` case.

```
dyninst-reattach-loop: /home/jistone/paradyn/dyninst/proccontrol/src/process.C:4418: bool int_thread::StateTracker::setState(int_thread::State): Assertion `generator_state == stopped || generator_state == exited || generator_state == detached' failed.
Aborted (core dumped)
```

[debug-proccontrol-asserted.zip](https://github.com/dyninst/dyninst/files/542922/debug-proccontrol-asserted.zip)

**Comment by mplegendre** [comment]
Josh,

There's at least a couple issues here.  The bad 'stat' call is an easy fix.  A thread exited during attach, after we identify that the LWP exists but before we read its stop state out of /proc/PID/status.  In that case we just have to drop the LWP from our list of things to attach to.  I can put in a small pull request for that one.

The hang is tougher.  We try to use a fix-point algorithm to attach to all threads, which looks something like this (see int_process::attachThreads() ).

do {
  found_new_threads = false
  getThreadLWPs(lwps)
  for each new lwp:
     createThreadAndAttach(lwp)
     found_new_threads = true
} while (found_new_threads);

The attach operation moves each thread to a stopped state, so in theory this should find all threads and get the process into a completely stopped state.  But I think we get in a race with the kernel where some thread gets created, but doesn't yet have a /proc/PID/task entry (so getThreadLWPs doesn't see it).  We stop that thread's parent, assume there are no more threads and exit this loop with a running and unknown thread.  We then wait for the thread attaches to complete (int_process::waitfor_startup).

You would expect that we'd then move on with a completely unknown thread in the process (which would also be very bad), but we additionally get tripped up by some BG/Q code (the attachThreads call at process.C:447).  That tries to re-issue thread attach operations, because BG/Q is weird about what order things happen in, and suddenly finds the new thread.  On Linux that call was supposed to be an idempotent nothing.  That's putting us into a weird state and leading to a hang.

I'm not sure how to best fix this.  Ideally, I'd prefer some way to have int_process::attachThreads realize there's a half-created kernel LWP and wait for it to become available.  Alternatively, we could try another fixpoint algorithm around both the attachThreads() and waitfor_startup() code, though that will require a decent reorganization of the already-complicated attach code.

**Comment by cuviper** [comment]
Thanks! The stat fix works well for me.

I'll try to confirm your hypothesis about the cause of the hang.  Some strategic systemtap probing ought to make this clear.  Then we'll see if I can come up with new ideas to fix it.

My hunch is that the fix-point loop needs to involve the actual stop events for each thread after attach.  That is, attach new threads, wait for some/all to stop, check for new threads, repeat.  Is that what you meant by involving the waitfor_startup() code?

**Comment by mplegendre** [comment]
Yes, that's what I meant about the waitfor_startup() code--adding a new wider-scoped fixpoint loop.

**Comment by wrwilliams** [comment]
So are we looking good to close this, or are there other lurking problems with this use case?

**Comment by cuviper** [comment]
I haven't found any more problems yet.  I'm going to up the ante today with higher thread counts in the mutatee, and see if anything else falls out...

**Comment by cuviper** [comment]
I just ran into that assertion again:
```
proccontrol/src/process.C:4437: bool int_thread::StateTracker::setState(int_thread::State): Assertion `generator_state == stopped || generator_state == exited || generator_state == detached' failed.
```

**Comment by cuviper** [comment]
Slightly more context: an added printf there shows me `handler:stopped generator:neonatal`.

**Comment by cuviper** [comment]
Another fix is in #259, and with this I've been running over an hour without a problem.

**Comment by wrwilliams** [comment]
With #259 merged is this finally ready to close?

**Comment by cuviper** [comment]
We are ~~certified~~ anecdotally race-free!
