### ISSUE TITLE
[ARM Decoding] Dyninst asserts when decoding some instructions.

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#334]
`4f 22 18 d5` corresponds to a system register instruction (I believe), and Dyninst terminates decoding with the exception: "tried to access system register not accessible in EL0"

**Comment by ssunny7** [comment]
This corresponds to a system register with encoding `0xc112` which the manual does not show as being any valid system register. What do the other compilers output for this?

**Comment by nathanhjay** [comment]
Other decoders output a generic form of the register that just prints the fields as parts of the register name. In this case, it would be: `msr s3_0_c2_c2_2, x16`. The general form is: `msr s<2+op0>_<op1>_c<crn>_c<crm>_<op2>, X<rt>`, where <expression> is replaced with the value of the expression.

**Comment by ssunny7** [comment]
I think what we're doing here is right. For the general form you mentioned above for implementation defined system registers. the only valid values that can be appended to 's' are 2 and 3 (since o0 is a 1-bit field), but the manual only lists s3_* registers - there is no mention of s2_*.

In addition, for s3_*, the crn field has to be of the form 1x11 which is not the case for `4f 22 18 d5`, so this cannot be a valid system register (at least not in EL0). Right now, we don't print the s3_* format for implementation defined system registers - we just print "IMPLEMENTATION_DEFINED_SYSREG" which is correctly getting printed for crn fields that match the 1x11 pattern.
