### ISSUE TITLE
force boost build and force boost install

### ISSUE THREAD

**Issue by lee218llnl** [dyninst/dyninst#374]
I would like to have build options to 1) force Dyninst to build its own boost and to 2) force Dyninst to install its own boost. This came up in the Travis build environment for STAT, which has boost 1.46.1 installed, which has a bug with shared_ptr (https://stackoverflow.com/questions/18900730/boostshared-ptrshared-ptrconst-boostshared-ptr-is-implicitly-declared). Dyninst sees the boost installation, but then fails to build. It would be nice if there were a cmake flag that tells Dyninst to download/build boost even if boost is already installed. I also think that Dyninst should install boost when it builds boost (either by default or a separate cmake flag). This also came up in Travis because I hacked Dyninst to build boost, and thus Dyninst built OK, but then I tried to build STAT, which used (via inclusion of Dyninst headers) the buggy 1.46.1 system boost installation.

**Comment by lee218llnl** [comment]
@tgamblin, @mplegendre: @wrwilliams said you may have some input here. As proposed, I don't think this will affect a Spack install of Dyninst, since Spack will use the Spack-built boost and would not specify the optional flags that I am requesting.

**Comment by tgamblin** [comment]
@lee218llnl: I don't see anything wrong with this.  If `dyninst` builds its own boost I do think it should probably install that `boost` -- otherwise what guarantee do you have that it'll work when installed?

I don't think this affects the spack-built `dyninst`, as long as the bundled boost build is disabled in the `dyninst` Spack package.  I believe the @wrwilliams already has flags to disable the external projects in his CMake build.

**Comment by wrwilliams** [comment]
@lee218llnl Does #381 work for you?

**Comment by lee218llnl** [comment]
looks good to me

**Comment by wrwilliams** [comment]
Great. I'll get that merged over and close this out.
