### ISSUE TITLE
Dyninst doesn't instrument the binary when it is compiled with -O3 flag (g++)

### ISSUE THREAD

**Issue by jmashruw** [dyninst/dyninst#384]
Hi,

I am trying to instrument a simple C++ code using Dyninst. It works perfectly fine when I compile the sample binary as follows
g++ hello.cpp -o hello

However, it fails to inject code when I compile the sample binary using -O3 flag:
g++ -O3 hello.cpp -o hello

Please find the link from where i was refering to implement code injection:

http://www.paradyn.org/release8.1/doc/DyninstAPI.pdf

I am following example program from pg no: 71 of the pdf

Any help will be appreciated. Thanks.

Regards,
Jinal

**Comment by wrwilliams** [comment]
@jmashruw That version of the manual is at least one major version behind our latest (see the PDFs in the doc/ directories in the repository or in share/doc in a recent install). There are quite a few changes to the examples from 8.x to 9.x, and if you've got a mismatched version (or a less-stable 8.x build) I'm not surprised that they don't work.

I'd start debugging this (assuming it's not a version mismatch or equivalent) by adding all of the error checking and handling code that we omit from most of our examples for clarity, so that you can identify more precisely what part of the instrumentation process is failing.

**Comment by jmashruw** [comment]
@wrwilliams  Thank you so much for your response.

I know I have been following older pdf.. But I confirmed my code from the documentation of dyninst 9.3.1 installation and it still fails for my scenario. There is no mismatched version in my opinion.

Please find attached my code for your reference. It might help you reproduce issue.

I look forward to hear from you soon.
[Dyninst-test-case.zip](https://github.com/dyninst/dyninst/files/1143430/Dyninst-test-case.zip)

Regards,
Jinal Mashruwala

**Comment by wrwilliams** [comment]
Yeah, that code looks sensible. What's the failure mode? Is patch.exe crashing? If so, where? Are we failing to generate a binary? Is the generated binary failing to load, crashing, or executing without the injected code?

**Comment by jmashruw** [comment]
@wrwilliams The code is crashing and executing without the injected code.

**Comment by jmashruw** [comment]
@wrwilliams  Is there any work around?

**Comment by mxz297** [comment]
@jmashruw I just looked at your code.  In your patch.cpp, there are three lines of code:
```
image->findFunction("foo1", func);
points = func[0]->findPoint(BPatch_entry);
```

Could you check whether the ```func```  actually have any elements inside?

Basically, I downloaded you code. When I compiled your mutatee (hello.cpp) under O3, the compiler inlined the instrumentation target function ```foo1``` into the main function. Since you ```foo1``` is simply calling cout to print a message, it is very likely that the compiler under O3 will inline this function. And I look at the disassembly from objdump:
```
00000000004008b0 <main>:
....
  4008b8:       0f be 73 43             movsbl 0x43(%rbx),%esi
  4008bc:       bf 80 10 60 00         mov    $0x601080,%edi
...
  4008e7:       e8 84 ff ff ff          callq  400870 <_ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l@plt>
...
  400907:       75 af                   jne    4008b8 <main+0x8>
```

You can clearly see that the main function directly call ostream in a loop without calling into foo1. So, from my guess, your mutator crashed because you are accessing an empty vector and the mutatee will never have the injected code because your instrumentation target does not actually exist.

**Comment by jmashruw** [comment]
@mxz297  Thank you so much.. It worked for me after i fixed for empty vector

**Comment by mxz297** [comment]
@jmashruw You are welcome! Close this one.
