### ISSUE TITLE
Error when starting DynInst: Segmentation fault

### ISSUE THREAD

**Issue by TeamVault** [dyninst/dyninst#387]
Hi all,

I start DynInst and I get the following error log. Any ideas:

./run-ta-static.sh server-bins/node 
Using bininfo prefix /home/peng/Tools/typearmor/out/binfo
+++ pwd
+++ pwd
++ sudo DYNINSTAPI_RT_LIB=/home/peng/Tools/dyninst-9.3.1/install/lib/libdyninstAPI_RT.so LD_LIBRARY_PATH=/home/peng/Tools/dyninst-9.3.1/install/lib:/home/peng/Tools/dyninst-9.3.1/install/lib:/install/lib::/usr/local/lib /home/peng/Tools/typearmor/bin/di-opt -load=/home/peng/Tools/typearmor/bin/fcfi_pass.di -fcfi_pass -binfo=/home/peng/Tools/typearmor/out/binfo -args /home/peng/Tools/typearmor/server-bins/node server-bins/node
FCFIPass: Running (runtime)...
FCFIPass: Command-line arguments given (opt*): 'at.txt'

FCFIPass: Reading AT functions...
FCFIPass: Performing static analysis on objects...
./run-ta-static.sh: line 45: 10003 Segmentation fault      (core dumped) sudo DYNINSTAPI_RT_LIB=$DI/lib/libdyninstAPI_RT.so LD_LIBRARY_PATH=$DI/lib:$LD_LIBRARY_PATH $DI_OPT -load=`pwd`/bin/fcfi_pass.di -fcfi_pass -binfo=$BINFO -args `pwd`/$exe $* 2> ta.log

**Comment by wrwilliams** [comment]
Can I get a stack trace from that core file?

**Comment by paulm1024** [comment]
Yes, sure, I'll provide it to you in approx. 10 hours, need access to my office PC.

**Comment by farzanehabazari** [comment]
I  have the same problem in running Typearmor: Segmentation Fault.
What should I do?

Thanks

**Comment by mxz297** [comment]
@farzanehabazari Typearmor is a tool written by developers outside Dyninst. As Dyninst developers, we do not have the expertise for solving problems showing up in Typearmor. 

It looks like that Typearmor is written with Dyninst-9.3.1, which was extremely old. I guess Typearmor is not longer maintained to keep up with new versions of Dyninst. We just release Dyninst 10.1, and since Dyninst-9.3.1, we have got many fixes. And it is unlikely to port all these fixes back to Dyninst-9.3.1.
