### ISSUE TITLE
Proccontrol int_process::waitAndHandleEvents ignores block flag

### ISSUE THREAD

**Issue by bwelton** [dyninst/dyninst#504]
int_process::waitAndHandleEvents takes a paremeter to specify whether or not to block. However this setting is ignored and it seems to result in a deadlock on process exit in certain circumstances. 

Is there any particular reason why this parameter is ignored?

**Comment by n738cu** [comment]
@sashanicolas and @hainest : Is this fixed given the recent proccontrol improvements?

**Comment by hainest** [comment]
@n738cu No, this is a separate issue.

@mplegendre Some quick archaeology shows that this parameter's use was removed in 76eb9d44 which has the commit message

    Major rewrite of process stop/continue decision mechanism:
    - Use Counter objects to track whether we should block in the main queue
    - Use multiple StateTracker objects in place of single InternalState to track whether to stop/continue

Is the parameter supposed to be ignored in favor of the counter objects?

**Comment by mplegendre** [comment]
The parameter's not ignored.  Check the comment about macros at https://github.com/dyninst/dyninst/blob/master/proccontrol/src/process.C#L1003 and checkBlock at https://github.com/dyninst/dyninst/blob/master/proccontrol/src/process.C#L976.

The original "deadlock on process exit" in this issue was likely something else, which perhaps could be the ghost thread issue.  But that's just a guess without a reproducer or specifics.

**Comment by hainest** [comment]
@mplegendre Thanks for the clarification.
