### ISSUE TITLE
Bpatch openBinary failed

### ISSUE THREAD

**Issue by pramodjayram** [dyninst/dyninst#608]
openBinary function for hex file compiled for ARMv8 (M23 processor) returns with error. Is there any solution for this?

**Comment by mxz297** [comment]
Dyninst can only understand ELF and PE formats. I don't think Dyninst currently supports HEX file. 

Unfortunately, I am not familiar with HEX file and I am not sure whether you can convert a HEX file to an ELF file so that Dyninst can understand it.

**Comment by pramodjayram** [comment]
Dyninst can read binary and executabl files. Hex files are similar to binary/executable files and most of the compilers generate either bin or hex files. Is there any work around?

**Comment by mxz297** [comment]
We use external libraries to understand binary format. For example, we use libelf from elfutils to parse ELF files. Therefore, Dyninst will need a similar library to understand HEX.  Or, if you can trick libelf to open a HEX file, then it is possible to workaround it. 

However, the problem is more than just reading the file format. I am guessing you want to do binary rewriting with HEX file because you are using BPatch interface. This means that Dyninst will also need to be able to add code to a HEX file format.

In addition, Dyninst's mechanism for instrumentation (for both dynamic instrumentation and binary rewriting) will create a new section to store instrumentation. A "section" seems to be a concept only applicable for executables. I don't think HEX file has the concept of sections. This means that there will be other changes inside Dyninst to perform binary rewriting on HEX file.

**Comment by pramodjayram** [comment]
I converted the output file from hex to elf format but I get the following error:

> /dyninst/dwarf/src/dwarfHandle.C:163: bool Dyninst::DwarfDyninst::DwarfHandle::init_dbg(): Assertion `0 && "Unsupported archiecture in ELF file."' failed.
> Aborted (core dumped)

Does Dyninst 10.0 version support ARMv8 binaries? I am trying for binary rewriting but it looks like it does not support ARMv8 architecture.

**Comment by mxz297** [comment]
Binary rewriting on ARMv8 is still under development, but Dyninst 10.1 (released a few weeks ago) has some initial support for binary rewriting. 

Since binary rewriting on ARMv8 is our current development focus, if Dyninst 10.1 does not work for you, can you please share your binary with us for better debugging?

**Comment by pramodjayram** [comment]
I have attached the binary file for ARMv8 architecture specifically M2351 processor. Please let me know if the below file works with the current dyninst version as it did not work for me.

[https://drive.google.com/file/d/1AhHOiOvmSG5j8vuB37BEu5W4stMHBY7u/view?usp=sharing](url)

Thank You

**Comment by mxz297** [comment]
@pramodjayram Thanks! I can download this file. 

@sashanicolas Can you also download and try to repeat this problem?

**Comment by pramodjayram** [comment]
Any updates regarding the support for ARMv8 architecture for the aove binary?

**Comment by sashanicolas** [comment]
@pramodjayram The binary you sent is:
```
/home/sasha/m23.elf: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV),
 statically linked, not stripped
```
It is not ARMv8, and we have not tested with 32 bit ELF. Also, statically linked is not supported yet. 
We are currently only supporting ARMv8, ELF 64 bit, and dynamic linked.

Also, your binary misses some sections. I can't tell for sure it will be a problem but I'm mostly sure we would need at least a .text section in it.

```
Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] ER_IROM1          PROGBITS        10040000 000034 009088 00  AX  0   0  4
  [ 2] ARM_LIB_STACK     NOBITS          30008000 0090bc 000800 00  WA  0   0  4
  [ 3] ER_IRAMVEC        NOBITS          30008800 0090bc 0001d8 00  WA  0   0  4
  [ 4] RW_IRAM1          PROGBITS        300089e0 0090bc 000068 00  WA  0   0  4
  [ 5] RW_IRAM1          NOBITS          30008b94 009124 001ef8 00  WA  0   0  8
  [ 6] ARM_LIB_HEAP      NOBITS          3000aa90 009124 00d570 00  WA  0   0  4
  [ 7] .debug_frame      PROGBITS        00000000 009124 000e58 00      0   0  1
  [ 8] .symtab           SYMTAB          00000000 009f7c 009020 10      9 1621  4
  [ 9] .strtab           STRTAB          00000000 012f9c 007d4c 00      0   0  1
  [10] .note             NOTE            00000000 01ace8 000028 00      0   0  4
  [11] .comment          PROGBITS        00000000 01ad10 00321c 00      0   0  1
  [12] .shstrtab         STRTAB          00000000 01df2c 000070 00      0   0  1
```
