### ISSUE TITLE
Variables in the BSS don't appear as variables.

### ISSUE THREAD

**Issue by woodard** [dyninst/dyninst#619]
int main(int argc, char **argv) {
        // Name the object file to be parsed:
        std::string file;
        if (argc == 1)
            file = "./raja-perf.exe";
        else
            file = argv[1];

        // Declare a pointer to an object of type Symtab; this represents the file.
        Symtab *obj = NULL;
        // Parse the object file
        bool err = Symtab::openFile(obj, file);

        if (err == false) exit(1);

        std::vector<Variable *> vars;
        if (!obj->getAllVariables(vars)) exit(3);
        // It looks like BSS variables are present but they are of unknown type.
        std::vector<Symbol *> syms;
        if (obj->findSymbol(syms, "__bss_start", Symbol::ST_UNKNOWN)) {
            std::cout << std::endl << syms[0]->getType() << std::endl;
        } else
            std::cout << "elsewhere" << std::endl;
        // but all the BSS variables don't appear in the list of variable.s
        vars.clear();
        if (obj->findVariablesByName(vars, "__bss_start")) {
        }

**Comment by woodard** [comment]
It is my expectation that uninitialized variables would be included in the list of variables which are returned by getAllVariables(). 

It is fine that it the underlying symbol exists but that isn't as useful.

**Comment by bwelton** [comment]
The variables in question are marked by Symtab as being of type ST_UNKNOWN. Because of this marking, they are never added the to the vector "everyVariable" in symtab (used by getAllVaribles to return all varibles, this vector is instantiated here: https://github.com/dyninst/dyninst/blob/896144c647d5ddb423bbfc6da338cda17ca24185/symtabAPI/src/Symtab.C#L887 ), resulting in them never being returned 

Is the typing ST_UNKNOWN correct for variables in the BSS section?  Also there is a bug at line 964 of the above function where we will dereference a null pointer if this line is ever reached (https://github.com/dyninst/dyninst/blob/896144c647d5ddb423bbfc6da338cda17ca24185/symtabAPI/src/Symtab.C#L964).

**Comment by mxz297** [comment]
I believe ST_UNKNOWN is a direct translation from elf. readelf says the following about __bss_start:

```
 34473: 00000000011cc4a8     0 NOTYPE  GLOBAL DEFAULT   27 __bss_start
```

Here, the type of the symbol is "NOTYPE", which is then translated as ST_UNKNOWN in Dyninst. Here 27 represents .bss section.

In my opinion, `_bss_start` is definitely different from a typical variable declared in the source code. I think other actual uninitialized variables will be included because those uninitialized variables have type "OBJECT":

```
   156: 00000000011d51d8     8 OBJECT  LOCAL  DEFAULT   27 sample_prob_str
   157: 00000000011d51d4     4 OBJECT  LOCAL  DEFAULT   27 prob_str_broken
```

Here these variables are also in section index 27, which is .bss. They have symbol type "OBJECT".

@woodard Why do you want to look up `__bss_start`?

**Comment by woodard** [comment]
Honestly, I don't have particular interest in __bss_start.
When I was constructing my example test case, I picked __bss_start because it was very obviously a global variable in the BSS and it would likely be in every binary that you would look at meaning that I wouldn't have to include a test binary.

**Comment by mxz297** [comment]
I guess my point is that __bss_start is a special case. I am fine with treating __bss_start not as a typical "Variable" because it is not. So, the fact that you did not find __bss_start in the variable list may not necessary be an issue. However, if you want to manipulate __bss_start, then it becomes an issue for leaving it out.

**Comment by sashanicolas** [comment]
@woodard @mxz297 
Should we investigate more and eventually include NOTYPE variables or drop this issue?

**Comment by woodard** [comment]
We can drop it
