### ISSUE TITLE
Static variables in ARM instruction decoder cause crashes

### ISSUE THREAD

**Issue by mxz297** [dyninst/dyninst#630]
There are static variables in the ARM instruction decoder. 

https://github.com/dyninst/dyninst/blob/29535f22c1a17581107140da3910ccf148b36372/instructionAPI/src/InstructionDecoder-aarch64.C#L96

They should be converted into `std::call_once`.

**Comment by sashanicolas** [comment]
This variable was added because the instruction table was being filled repetitively every time an InstructionDecoder would be created. Theoretically it shouldn't cause a race condition, because the threads would be doing the same thing but multiple times. 
I don't know why this is the way chosen with ARMv8 but the other platforms do it differently.

**Comment by mxz297** [comment]
Multiple threads can check `built_insn_table` at the same time; all threads see `false`; and all continue to do the initialization.

This is a standard case of why static variable is typically not thread safe.

**Comment by blue42u** [comment]
@sashanicolas: To clarify, the instruction entries are inserted into a `std::vector`. If more than one thread decides to fill it, they will race on the memory management (in particular, growing the vector). In most cases this is an immediate crash as the threads double-free the old vector backing memory.

If possible it might be better to rewrite it as a `const` global initialized by a constant, that way it can be constructed at `_init` time before any threads start, or burned into the `.data` section if no construction is needed.
