### ISSUE TITLE
static instrumentation on statically linked ARMv8 binary and run without dynamic library

### ISSUE THREAD

**Issue by caihuali95** [dyninst/dyninst#674]
I am trying static instrumentation on a statically linked binary on AArch64.
But the mutator is aborted on 

> dyninst/dyninstAPI/src/parse-aarch64.C:320: bool BinaryEdit::doStaticBinarySpecialCases(). 

It seems that it is not supported right now, right?

By the way, I am also trying to link libdyninstAPI_RT.a statically, rather than using libdyninstAPI_RT.so.10.1. I am not sure how to do it and I wonder whether it is possible.

I found this (https://github.com/dyninst/dyninst/issues/428) saying that it is not possible without significant work. Is it still true in Dyninst 10.1?

**Comment by hainest** [comment]
>It seems that it is not supported right now, right?

ARMv8 support is a work in progress. I will ask our ARM developer if that should be working or not.

>By the way, I am also trying to link libdyninstAPI_RT.a statically, rather than using libdyninstAPI_RT.so.10.1. I am not sure how to do it and I wonder whether it is possible.

You need pass `-DENABLE_STATIC_LIBS` to the Dyninst CMake configuration. To link to the static libraries, you need to specify each one you use during the link step. This can be a pain as it's not entirely obvious which ones you'll need. If you are using linux, you can find all of the static libraries in your Dyninst installation using `find /your/Dyninst/install/path -name "*.a"`.

>I found this (#428) saying that it is not possible without significant work. Is it still true in Dyninst 10.1?

That issue is about trying to patch a binary without using the Dyninst Runtime (which is still not possible). You can patch binaries using the static Dyninst Runtime.

**Comment by sashanicolas** [comment]
@caihuali95 Statically linked binaries are not supported yet. The function  `BinaryEdit::doStaticBinarySpecialCases()` has an `assert(0)` because it has not been implemented.
