### ISSUE TITLE
Questionable location list for main.cold function

### ISSUE THREAD

**Issue by wcohen** [dyninst/dyninst#717]
**Intention**

Trying to check that each of the location ranges match up with instruction boundaries and are within the function (or global).  Have example code at https://github.com/wcohen/quality_info/blob/master/dyninsttools/locrangechecks.C

**Describe the bug**

When running the locrangecheck tool on the binutils gold linker (ld-new) built on Fedora 30.  A number of the locations are marked as outside the current function main.cold.  For example it seems to be fetching the main function variable location lists for the main.cold function.  I verified that the function being inspected is main.cold, the function start address (f->addr())matches the start of main.cold.

**To Reproduce**

On Fedora30

wget https://kojipkgs.fedoraproject.org//packages/binutils/2.31.1/29.fc30/src/binutils-2.31.1-29.fc30.src.rpm
sudo dnf build-dep binutils-2.31.1-29.fc30.src.rpm
rpm -Uvh binutils-2.31.1-29.fc30.src.rpm
cd rpmbuild/SPEC
rpmbuild -ba binutils.spec
git clone https://github.com/wcohen/quality_info
cd quality_info/dyninsttools
make
./locrangechecks ~/rpmbuild/BUILD/binutils-2.31.1/gold/ld-new 

End up seeing:

# main.cold start:0x37410 
name=argc lowPC=3e540 hiPC=3e57c stClass=2 refClass=2
name = argc, k.lowPC=0x3e540 outside function
name = argc, k.hiPC=0x3e57c outside function
name = argc, k.lowPC=0x3e540 not valid boundary
name = argc, k.hiPC=0x3e57c not valid boundary
name=argc lowPC=3e57c hiPC=3e5a4 stClass=3 refClass=2
name = argc, k.lowPC=0x3e57c outside function
name = argc, k.hiPC=0x3e5a4 outside function
name = argc, k.lowPC=0x3e57c not valid boundary
name = argc, k.hiPC=0x3e5a4 not valid boundary
name=argc lowPC=3e57c hiPC=3e5a4 stClass=3 refClass=2
...

**Expected behavior**
Expect to get location list for the specific function being requested.

**System (please complete the following information):**
 - What platform  x86_64
 - What commit? dyninst-10.1.0-4.fc30.x86_64 on fedora 30
 - Maybe libc version glibc-2.29-28.fc30.x86_64

**Additional context**

**Comment by n738cu** [comment]
@sashanicolas and @hainest : Any response for this?

(@mxz297 )

**Comment by kupsch** [comment]
I am able to recreate this issue, by building the latest dyninst repo, and the dyninst/examples repo on the host coriander.cs.wisc.edu (Ubuntu 20.04, gcc 9.3.0, ld 2.34).  I ran the codeCoverage example as described in its README.md:

```bash
export LD_LIBRARY_PATH=$DYNINST_INSTALL/lib:$LD_LIBRARY_PATH
export DYNINSTAPI_RT_LIB=$DYNINST_INSTALL/lib/libdyninstAPI_RT.so
./code_coverage -sb ./testcc testcc.inst

LD_LIBRARY_PATH=$(pwd):$LD_LIBRARY_PATH ./testcc.inst
```

The result is non-deterministic, when starting with the same input same input directory (files in attached [codeCoverage-initial.tar.gz](https://github.com/dyninst/dyninst/files/4984109/codeCoverage-initial.tar.gz)) of the built codeCoverage directory of dyninst/examples, instrumenting and running as above, the output of `./testcc.inst` is either as expected (files in attached [codeCoverage-good.tar.gz](https://github.com/dyninst/dyninst/files/4984112/codeCoverage-good.tar.gz)) or fails (files in attached [codeCoverage-bad.tar.gz](https://github.com/dyninst/dyninst/files/4984113/codeCoverage-bad.tar.gz)) due to the dynamic linker being unable to locate the exitCoverage functions cold symbol.

```
./testcc.inst: symbol lookup error: ./testcc.inst: undefined symbol: _Z12exitCoverageiii.cold
```

In the good case the requested symbol is _Z12exitCoverageiii which is exported in libInst.so, and in the bad case the requested symbol if _Z12exitCoverageiii.cold which is not dynamically exported (but does exist as a local static symbol).

**Comment by ZanderChang** [comment]
I met the same problem when testing [csi-afl](https://github.com/Vul4Vendetta/csi-afl), it uses dyninst to add a dynamic library to the target but instrument the function `_Z17initAflForkServerjPKc.cold` sometimes, which is not exported.

**Comment by ZanderChang** [comment]
Oh, just removing `-O3` works fine and the generated `libCSIDyninst.so` contains no symbols ending with `.cold`.

**Comment by wcohen** [comment]
Recompiling with lower optimization levels is not really an option.  It looks like the name() method is stripping of the .cold suffix off.  Is there some way to get the original raw name?

**Comment by kupsch** [comment]
Pull request #889 when released should fix the problem you are experiencing.  You can build Dyninst from the tip of the branch demangler if you'd like to test this fix.
