### ISSUE TITLE
'make' acts like 'make install'

### ISSUE THREAD

**Issue by mplegendre** [dyninst/dyninst#726]
While trying to build master to test the DWARF line bug report I made yesterday I did a 'make' command on an existing build area to see if it built.  This 'make' started installing files, as if I'd done a 'make install'.  

The build then broke on RHEL7/x86_64--looks like it tried to use the system boost rather than the one DyninstAPI downloaded and installed.

But in the middle of the build it started installing files.  I turned up with half an install over an old one, and this broke a production deployment of Dyninst.  I hadn't intended to 'make install' that build.

Please change to have 'make' act with the expected semantics of not installing.

**Comment by hainest** [comment]
Hi, Matt.

This has been [documented](https://github.com/dyninst/dyninst/wiki/Building-Dyninst) behavior since 10.1 was released. The behavior changed in order to have the test suite use the same dependency binaries as Dyninst to fix subtle linker errors that arose when the test suite and Dyninst didn't use the same version of a dependency. The underlying issue is that Dyninst cannot correctly rpath its dependencies when it builds them from source. This requires that when `make install` is run for a dependency, it has to put it in a known location that is accessible after the build. The files that are being installed in this step are just the dependencies, no Dyninst files have been built yet.

The overall fix for this is to use target-dependent linking to allow for rpath adjustments during relinking (link/rpath once during `make` and link/rpath again during `make install`) which requires re-writing much of the build system to transition to CMake 3.0+. It's been on my list of things to do since the 10.1 release, but it's been pushed down several times.

There are a few ways around this:

1. Set CMAKE_INSTALL_PREFIX to a location distinct from a previous build and accessible during `make`.

2. Use spack to build Dyninst

3. Use the build script to build Dyninst

4. Install the dependencies yourself and point to them using the new configuration [variables](https://github.com/dyninst/dyninst/wiki/Building-Dyninst#configuration).

Ultimately, I want to get rid of Dyninst managing its own dependencies. It just adds unneeded maintenance. We've started to take steps toward that with the [sterile build](https://github.com/dyninst/dyninst/wiki/third-party-deps#sterile_build) option which doesn't allow them to be downloaded/built.
