### ISSUE TITLE
Problems with Instruction API parsing x86-64 binaries: sqrtsd

### ISSUE THREAD

**Issue by jmellorcrummey** [dyninst/dyninst#79]
The current master version of dyninst has problems parsing several instructions in x86-64 binaries. Below, I provide an example of an instruction that failed to parse (the first instruction) and the instruction following. This example was uncovere using the checkparse regression test developed at Rice and provided to Wisconsin.

**Application example: soliton**

problematic instructions:
`         sqrtsd    instruction length mismatch (xed length=5, instruction api length=4)`

example in context:
 ```
 404203:       f2 0f 51 04 d0          sqrtsd (%rax,%rdx,8),%xmm0 <<<----------------
 404208:       66 0f 2e c0             ucomisd %xmm0,%xmm0
```

**Comment by jdetter** [comment]
@jmellorcrummey  It is possible for me to have access to the binary for this?

**Comment by wrwilliams** [comment]
I have this binary and can make it accessible assuming that's okay with @jmellorcrummey, but generally I'd prefer that we cons up some trivial test cases for these rather than relying on particular binaries.

**Comment by jmellorcrummey** [comment]
I already forwarded the binary to John off list.
--
John Mellor-Crummey         Professor
Dept of Computer Science    Rice University
email: johnmc@rice.edu      phone: 713-348-5179

**Comment by wrwilliams** [comment]
Thanks, John. And @jdetter, the trivial test case comment still stands. :)

**Comment by jdetter** [comment]
@bill I have a source file with all of the VEX instructions in it that I've been using for testing, however there isn't a way to force GCC to use a specific VEX prefix for an instruction so for most of the issues we see are just missing entries in the tables where I couldn't produce that instruction with that prefix. Most of these issues can be fixed by copying table rows for the missing instructions for those prefixes. 

We talked about this during a meeting but I couldn't find a way to force GCC to use a specific prefix. I've used Peach a bit to help with the debugging but the output is still really noisy. Once we have our instructions in AT&T syntax I think we can get Peach to the point where it would be really useful for debugging the VEX implementation.
