### ISSUE TITLE
test5_7 failure on coriander

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#852]
This fails at [test5_7.C:82](https://github.com/dyninst/testsuite/blob/master/src/dyninst/test5_7.C#L82) when `index`==4 (i.e., the inst point is [`template_test::func_cpp`](https://github.com/dyninst/testsuite/blob/master/src/dyninst/test5_7_mutatee.C#L69)). The root cause is that the target edge in the CFG says the callee is `__stack_chk_fail` at address 0x4215744. But calling `getPltFuncs` on the image says that function is at 0x4215088. The gdb log contains the details ([test5_7.gdb.log](https://github.com/dyninst/dyninst/files/5229463/test5_7.gdb.log)).

@mxz297 I'm out of my depth here, so I have no idea where to go next. Do you have any thoughts? This is on coriander under my home directory. You have sudoer privileges there, so you can go re-run this, if you like. My gdb config is

    gdb --args ./test_driver -g++ -none -64 -create -dynamiclink -nonpic -test test5_7 -log tmp.log
    set env OMP_NUM_THREADS=2
    set env DYNINSTAPI_RT_LIB=/home/tim/paradyn/cMYYZBGM/dyninst/lib/libdyninstAPI_RT.so
    set env LD_LIBRARY_PATH=/home/tim/paradyn/cMYYZBGM/testsuite/tests:/home/tim/paradyn/cMYYZBGM/dyninst/lib:/var/software/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/perl-5.30.2-2zeizvc4oxifswn43n25of2d2mc645gk/lib:/var/software/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/libxml2-2.9.10-folxclnhb4zjtfo7xorl2o25iuswdlst/lib:/var/software/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/intel-tbb-2020.2-hqa5vzggodkis5bca2d7cudhzy3vwyxd/lib:/var/software/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/elfutils-0.179-wrifubs3rbr6lqviq266kaeiaeorji5e/lib:/var/software/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/boost-1.73.0-tkvazvirvs6mnongrmrqbkmklve6cf5n/lib
    handle SIGUSR2 nostop
    b test5_7.C:82 if index==4

This is the second half of #778

**Comment by mxz297** [comment]
I can reproduce this failure on coriander. It looks like the root cause here is a new style of PLT for Intel CET. This new style of PLT splits a plt stub into two pieces. Obivously, the cfg finds one part and the relocation finds another one. More description about the new style of PLT can be seen here: https://reviews.llvm.org/D59780

It is not directly obvious to me that why this new style of PLT will impact instrumentation as we currently do not instrument PLT stubs.

**Comment by hainest** [comment]
@mxz297 That explains why I was seeing this with gcc-9.3 no x86, but not gcc-9.3 on PowerPC. I'll try using an older gcc on coriander and see if it persists.

Would a temporary fix be to look up PLT functions by name instead of address?

**Comment by mxz297** [comment]
My first thought is that we should ignore the function call points, for which we cannot get the callee. This is because it is entirely possible to have an indirect call, where we cannot find the callee. 

However, after we change that from failing the test to continue to the next point. The test seems to hang...
