### ISSUE TITLE
How to instrument function from binary in Dyninst

### ISSUE THREAD

**Issue by ManojKumarChauhan** [dyninst/dyninst#863]
For a running process, Dyninst allows to instrument/wrap/replace functions. Generally we keep the instrumented or wrapped function in a shared library. As an example, running process contains func1 and func2. Shared library contains func3 and func4. Func3 is instrumented at the entry point of fun1 and func4 is wrapped for func2. Instead of keeping fun3 and fun4 in a shared library, Is it possible to keep them in a binary? I think it should be possible because we get the instructions of fun3 and func4 and write them in running process. If it's possible then please suggest how to do this. Please share if there is an example.

**Comment by mxz297** [comment]
@ManojKumarChauhan What you describe is a nice feature to have but not yet supported in Dyninst... 

The new code is often in a shared library so that the loader will take care of loading the library into the address space and the relocations for code and data. What you want to achieve essentially requires either Dyninst can perform relocation as what a dynamic loader would do or the user injects inlined assembly (essentially taking care of the positioning of code and data yourself).

**Comment by ManojKumarChauhan** [comment]
Will it be supported in future? Should I close this issue or keep it open?

**Comment by mxz297** [comment]
I don't think this is going to happen in the near future... You can keep it open and if other people have similar interests, its priority can go up.
