### ISSUE TITLE
dyn_regs.h missing SVE registers

### ISSUE THREAD

**Issue by woodard** [dyninst/dyninst#885]
There is probably a lot more to full enablement of SVE needed than just this but dyn_reg.h is missing the aarch64 SVE registers.

**Comment by hainest** [comment]
@woodard Are your current builds/tests failing because these instructions are missing?

@sashanicolas Do you have any thoughts on how much work this would be to implement?

@mxz297 It looks like Capstone supports these instructions in their `next` branch. I know we were initially going to only add support for x86 through Capstone, but how much more effort would it be to bring in ARM support, as well?

**Comment by mxz297** [comment]
> @mxz297 It looks like Capstone supports these instructions in their `next` branch. I know we were initially going to only add support for x86 through Capstone, but how much more effort would it be to bring in ARM support, as well?

@hainest Pure instruction decoding support for ARM is not difficult. But capstone has even more instruction operand read/write information entries missing. Considering that there has been no progress at all for Capstone to accept my improvement of read/write access entries for x86, I am not optimistic that we will switch decoder any time soon for ARM.

**Comment by hainest** [comment]
@mxz297 Should we just manually add these SVE registers for now?
